---
- name: Preparando equipo para configuracion minima
  gather_facts: True
  hosts: nuevos
  tasks:
     - name: Registrando Sistema en Portal de Red Hat.
       redhat_subscription:
             state: present
             username: "{{ satellite_deployment_rhn_user }}"
             password: "{{ satellite_deployment_rhn_password }}"
             consumer_name: "{{ satellite_deployment_hostname_full }}"
       tags:
          - "rhn"
          - "skip_ansible_lint"

     - name: "Validando si el equipo esta registrado en RHN"
       shell: "/usr/sbin/subscription-manager list --consumed --matches='*Satellite*' | awk '/Pool ID/ {print $3}'"
       tags:
          - "rhn"
          - "skip_ansible_lint"
       register: "satellite_deployment_subscribed"
       
     #Obteniendo pool_id que contiene satellite
     - name: "RHN | Obteniendo RHN pool id"
       shell: "/usr/sbin/subscription-manager list --all --available
         --matches='*Satellite*' | awk '/Pool ID/ {print $3}' | head -1"
       tags:
         - "rhn"
       register: "satellite_deployment_pool_id_command"
       ignore_errors: "yes"
       when: "{{ satellite_deployment_pool_id is undefined }}"
       
 
     - name: "Asignando pool_id como variable"
       set_fact:
         "satellite_deployment_pool_id": "{{ satellite_deployment_pool_id_command.stdout }}"
       when: "{{ satellite_deployment_pool_id is undefined }}"

#Asignando equipo a pool_id
     - name: "RHN | asignando pool id al equipo"
       command: "/usr/sbin/subscription-manager attach --pool={{ satellite_deployment_pool_id }}"
       tags:
         - "rhn"
         - "skip_ansible_lint"
       ignore_errors: "yes"
       when: "{{ satellite_deployment_subscribed.stdout == '' }}"

#Habilitando repositorios.
     - name: "RHN | habilitando repositorios necesarios"
       command: "/usr/sbin/subscription-manager repos --disable '*' --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.2-rpms "
       tags:
         - "rhn"
         - "skip_ansible_lint"
         
#Asegurando que RSM no esta configurado para usar una version en especifica de S.O.
     - name: "RHN | habilitando repositorios"
       command: "/usr/sbin/subscription-manager release --unset"
       tags:
         - "rhn"
#Limpiando medatada de los repositorios.
     - name: "Limpiando metadata de los repositorios."
       command: "yum clean all"
       tags:
         - "rhn"
