---
- name: Preparando equipo para configuracion minima
  hosts: all
  gather_facts: True
  tasks:
      - name: Actualizando Sistema Operativo
        yum:
          name: '*'
          state: latest
#Install the base software
      - name: Install software
        yum:
          name: satellite
          state: latest

          
