---
- name: Preparando equipo para configuracion de Red
  gather_facts: True
  hosts: nuevos
    vars_files:
    - /vars/variable_red.yaml
  tasks:
     - name: "Asignando IP a interfaz de Red"
       shell: "nmcli con mod {{ satellite_deployment_net_interface }} ipv4.addresses '{{ satellite_deployment_ip_address }}/{{ satellite_deployment_net_prefix }}'"
       tags:
           - "set_network"

     - name: "Asignando GW a IP"
       shell: "nmcli con mod {{ satellite_deployment_net_interface }} ipv4.gateway {{ satellite_deployment_gw_address }}"
       tags:
         - "set_network"

     - name: "Asisgnando metodo manual a interfaz de red"
       shell: "nmcli con mod '{{ satellite_deployment_net_interface }}' ipv4.method manual"
       tags:
         - "set_network"

     - name: "Configurando interfaz de red red en autoconnect"
       shell: "nmcli con mod {{ satellite_deployment_net_interface }} connection.autoconnect yes"
       tags:
         - "set_network"

     - name: "iniciando interfaz de red (UP)"
       shell: "nmcli con up {{ satellite_deployment_net_interface }}"
       tags:
         - "set_network"
