# Las tasks deben estar definidas en el fichero main.yml
# o en cualquier otro fichero .yml siempre y cuando se -
# haga referencia a ellos desde el main.yml
---
- name: PLAYBOOK DE TAREAS POS-INSTALACIÓN RHEL 7
  gather_facts: True
  hosts: nuevos
  tasks:

- name: Nombre de Host
  include: 1_registro-rhn.yaml
  ignore_errors: True
#- include: set_facts.yml
#- include: registro-rhn.yaml
#- include: network.yml
#  when: "{{ satellite_deployment_set_network }}"
#- include: firewall.yml
- include: 2_install_software
#- include: install_satellite.yml
#- include: configure_satellite.yml
#- include: configure_capsule.yml
